name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.0
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'www.luismendeze.com'
          exclude: '.*\.md$|.gitignore$|.git\/.*$|.github\/.*$'
